### ISSUE TITLE
[EasyLang] Site corrections

### ISSUE THREAD

**Issue by zavizionnaya** [easably/landing-page#15]

**Comment by zavizionnaya** [comment]
Правки сайта:
1. Основной текст везде Open Sans (страницы about, products. download);
2. Блог временно скрываем (и на первой странице, и из меню). В меню можно оставить, но тогда нужна страница-заглушка; 
3. На главной странице убрать полосу между первым и вторым блоком (шапка и УТП);
4. Неверный вес логотипов программ в блоке "скачать". Они должны быть крупнее цифр из предыдущего блока, а сейчас они мельче.  В названии тьютора указать статус Beta;
5. В блоке "отзывы" скрыть фон, цвет плашек под текстом сделать таким: EEEEEE
6. У кота в подвале "подрезано" ухо. Верните ухо!!!
7. кегль основного меню увеличить (до уровня Try our app).

**Comment by MikitaAleksandrovich** [comment]
Fixed 
https://github.com/easably/website/commit/3ec17b1b273251f3d09703bbd42f6f840a4610e2
